// DisplayJSONFiles.idl : IDL source for DisplayJSONFiles.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DisplayJSONFiles.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(A978393E-6AEB-4F88-933D-EE8395EE38C6),
		dual,
		helpstring("IWinMergeScript Interface"),
		pointer_default(unique)
	]
	interface IWinMergeScript : IDispatch
	{
		[propget, id(1), helpstring("property PluginEvent")] HRESULT PluginEvent([out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property PluginDescription")] HRESULT PluginDescription([out, retval] BSTR *pVal);
		[propget, id(3), helpstring("property PluginFileFilters")] HRESULT PluginFileFilters([out, retval] BSTR *pVal);
		[propget, id(4), helpstring("property PluginIsAutomatic")] HRESULT PluginIsAutomatic([out, retval] VARIANT_BOOL *pVal);
		[id(5), helpstring("method UnpackBufferA")] HRESULT UnpackBufferA([in] SAFEARRAY(unsigned char) * pBuffer, [in] INT * pSize, [in] VARIANT_BOOL * pbChanged, [in] INT * pSubcode, [out, retval] VARIANT_BOOL * pbSuccess);
		[id(6), helpstring("method PackBufferA")] HRESULT PackBufferA([in] SAFEARRAY(unsigned char) * pBuffer, [in] INT * pSize, [in] VARIANT_BOOL * pbChanged, [in] INT subcode, [out, retval] VARIANT_BOOL * pbSuccess);
		[id(7), helpstring("method UnpackFile")] HRESULT UnpackFile([in] BSTR fileSrc, [in] BSTR fileDst, VARIANT_BOOL * pbChanged, INT * pSubcode, [out, retval] VARIANT_BOOL * pbSuccess);
		[id(8), helpstring("method PackFile")] HRESULT PackFile([in] BSTR fileSrc, [in] BSTR fileDst, VARIANT_BOOL * pbChanged, INT pSubcode, [out, retval] VARIANT_BOOL * pbSuccess);
		[id(9), helpstring("method ShowSettingsDialog")] HRESULT ShowSettingsDialog([out, retval] VARIANT_BOOL * pbHandled);
	};

[
	uuid(FDADED2E-6E39-47BB-99BB-BA028F251B29),
	version(1.0),
	helpstring("DisplayJSONFiles 1.0 Type Library")
]
library DisplayJSONFilesLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(E56B02C7-15F5-4A2C-A5D9-21D9E371A392),
		helpstring("WinMergeScript Class")
	]
	coclass WinMergeScript
	{
		[default] interface IWinMergeScript;
	};
};
